-- ============================================================
-- Migration 003: Inicialização limpa
-- ============================================================
-- Nenhum dado fictício inserido.
-- O administrador principal é: kigutifenix@gmail.com
-- Cadastre caminhões e motoristas reais pela interface do sistema.
-- ============================================================
